### ISSUE TITLE
Header design WideScreen

### ISSUE THREAD

**Issue by EmpyreanMist** [EmpyreanMist/Kino---Cinema#34]
User wants header design inspired by Hacker Escape Rooms and colors from nfbio when users screen is wider than 1200px . The picture and the button are not part of the header.

Example: ![Image](https://github.com/user-attachments/assets/7e64dd3a-e6aa-481f-b1d6-d20b510a3e59)

**Comment by jan-elia-24** [comment]
Link for PR: https://github.com/EmpyreanMist/Kino---Cinema/pull/97
