### ISSUE TITLE
Add picture underneath header nav in home page

### ISSUE THREAD

**Issue by itsJoel59** [EmpyreanMist/Kino---Cinema#73]
Add a specific picture underneath the header nav in home page. 

Picture:
https://cdn.discordapp.com/attachments/1316404424050081802/1318930622198059118/360_F_281849878_0Memw2hdFHyggA8gmK6rc8QSU9JnjYba.png?ex=67641d5c&is=6762cbdc&hm=f9d02d1e7a012df4b84b4c7d75215c9c1710fd82897f43248ff45615db254fd7&

**Comment by EmpyreanMist** [comment]
![image](https://github.com/user-attachments/assets/38c252e7-5e5e-40e9-ba53-4820c9c0a7eb)
